service: js-lambda
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1

functions:
  first:
    handler: first.hello
  second:
    handler: second.hello
  hello:
    handler: src/hello.handler

  costNotifier:
    handler: src/costNotifier.handler
    events:
      - schedule: cron(0 0 * * ? *)
    environment:
      SLACK_WEBHOOK_URL: ${ssm:cost_notifier_url}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ce:GetCostAndUsage
        Resource: '*'