service: todo-app
frameworkVersion: '3'

plugins:
  - serverless-webpack
  - serverless-iam-roles-per-function
  - serverless-api-gateway-throttling

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 10
    maxConcurrentRequests: 5

provider:
  name: aws
  runtime: nodejs16.x
  region: ap-northeast-1

functions:
  hello:
    handler: src/hello.handler
    events:
      - httpApi:
          method: get
          path: /hello

  costNotifier:
    handler: src/costNotifier.handler
    events:
      - schedule: cron(0 0 * * ? *)
    environment:
      SLACK_WEBHOOK_URL: ${ssm:cost_notifier_url}
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ce:GetCostAndUsage
        Resource: '*'